name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTION_PK }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEBIAN_SERVER_HOST }}
          username: ${{ secrets.DEBIAN_SERVER_USERNAME }}
          key: ${{ secrets.ACTION_PK }}
          script: |
            set -e  # Arrêter l'exécution en cas d'erreur
            cd ~
            if [ -d special-sniffle ]; then
              rm -rf special-sniffle
            fi
            git clone --branch main git@github.com:leopoldch/special-sniffle.git
            cd special-sniffle
            npm install
            npm run build
            sudo /bin/systemctl restart sniffle.service
