name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEBIAN_SERVER_HOST }}
          username: ${{ secrets.DEBIAN_SERVER_USERNAME }}
          key: ${{ secrets.ACTION_PK }}
          script: |
            cd ~/special-sniffle
            git pull origin main
            npm install --production
            npm run build
            sudo systemctl restart special-sniffle.service
