name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sniffler:latest
          platforms: linux/amd64,linux/arm64

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Debian Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEBIAN_SERVER_HOST }}
          username: ${{ secrets.DEBIAN_SERVER_USERNAME }}
          password: ${{ secrets.DEBIAN_SERVER_PASSWORD }}
          key: ${{ secrets.DEBIAN_SERVER_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/sniffler:latest
            docker stop sniffler || true
            docker rm sniffler || true
            docker run -p  3005:3005 \
                       -d --restart always --name sniffler \
                       ${{ secrets.DOCKER_USERNAME }}/sniffler:latest